import type { CategoryIcon } from '@shared/settings'
import {
  AlertCircleIcon,
  BellIcon,
  BookmarkIcon,
  Briefcase as BriefcaseIcon,
  Building2Icon,
  CalendarIcon,
  ClockIcon,
  CodeIcon,
  CreditCardIcon,
  DollarSignIcon,
  FileTextIcon,
  FlagIcon,
  FolderIcon,
  GiftIcon,
  GlobeIcon,
  HeartIcon,
  HomeIcon,
  InboxIcon,
  LockIcon,
  type LucideIcon,
  MailIcon,
  MegaphoneIcon,
  NewspaperIcon,
  PackageIcon,
  PaperclipIcon,
  ReceiptIcon,
  ShieldIcon,
  ShoppingCartIcon,
  SparklesIcon,
  StarIcon,
  TagIcon,
  UsersIcon,
  ZapIcon
} from 'lucide-react'

export const CATEGORY_ICON_MAP: Record<CategoryIcon, LucideIcon> = {
  Tag: TagIcon,
  Mail: MailIcon,
  Inbox: InboxIcon,
  Receipt: ReceiptIcon,
  ShoppingCart: ShoppingCartIcon,
  Package: PackageIcon,
  Newspaper: NewspaperIcon,
  Bell: BellIcon,
  Megaphone: MegaphoneIcon,
  Star: StarIcon,
  Heart: HeartIcon,
  Bookmark: BookmarkIcon,
  Flag: FlagIcon,
  Briefcase: BriefcaseIcon,
  Building2: Building2Icon,
  Users: UsersIcon,
  FileText: FileTextIcon,
  Folder: FolderIcon,
  CreditCard: CreditCardIcon,
  DollarSign: DollarSignIcon,
  Gift: GiftIcon,
  Calendar: CalendarIcon,
  Clock: ClockIcon,
  Paperclip: PaperclipIcon,
  Lock: LockIcon,
  Shield: ShieldIcon,
  Zap: ZapIcon,
  Sparkles: SparklesIcon,
  Code: CodeIcon,
  Globe: GlobeIcon,
  Home: HomeIcon,
  AlertCircle: AlertCircleIcon
}

export function categoryIconComponent(name: CategoryIcon | null | undefined): LucideIcon {
  if (!name) return TagIcon
  return CATEGORY_ICON_MAP[name] ?? TagIcon
}
